/// Flutter icons Icon_app
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Icon_app
///      fonts:
///       - asset: fonts/Icon_app.ttf
///
///
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Fontelico, Copyright (C) 2012 by Fontello project
///         Author:    Crowdsourced, for Fontello project
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://fontello.com
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Typicons, (c) Stephen Hutchings 2012
///         Author:    Stephen Hutchings
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://typicons.com/
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class Icon_app {
  Icon_app._();

  // static const _kFontFam = 'Icon_app';
  // static const String? _kFontPkg = null;
  //
  // static const IconData close = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  // static const IconData code = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  // static const IconData delete = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  // static const IconData t4t = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  // static const IconData format_italic = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  // static const IconData format_list_bulleted = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  // static const IconData format_list_numbered = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  // static const IconData format_strikethrough = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  // static const IconData format_underlined = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);

}
